ss=("Question one")
print(ss)
name=("FATIMA SALAHUDEEN")
print(name)
bb=("science education")
print(bb)
rr=("Question two")
print(rr)
scare=("boo")
print(scare)
tt=("Question three")
print(tt)
yh=(2)
print(yh)
kl=(3)
print(kl)
bo=(2+3)
print(bo)
dr=("Question four")
print(dr)
outcome=(12/0.5)
print(outcome)
ff=("Question five")
print(ff)
variable=(2+3)
print(variable)
g=("Question six")
print(g)
k=("modullus%")
print(k)
s=("Question seven")
print(s)
k=(2*4)*(4+2)
print(k)